#! /bin/bash

DBPath="${DBPath:-/var/lib/pacman/}"
eval $(awk -F' *= *' '$1 ~ /DBPath/ { print $1 "=" $2 }' /etc/pacman.conf)

mkdir -p /var/lib/pacman-next/
ln -s "${DBPath}/local" /var/lib/pacman-next/
